ТЗ 11
IvanRosokhach/java-filmorate pull request #7
Opened 2023-03-12 00:04 UTC by IvanRosokhach

2023-03-12 14:07 UTC, db-exp requested changes

2023-03-12 14:07 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            throw new NotFoundException(String.format(UserStorage.notFoundUser, userId));
в userDbStorage уже кидается ошибка при findBy - может лучше его использовать?

2023-03-12 14:07 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            throw new NotFoundException(String.format(UserStorage.notFoundUser, userId));
в userDbStorage уже кидается ошибка при findBy - может лучше его использовать?

2023-03-12 14:07 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +    public Collection<User> getCommonFriends(long id, long otherId) {
тут в методе тоже лучше кмк использовать findBy вместо exists

2023-03-12 22:32 UTC, IvanRosokhach commented
Возможно слегка перегнул... Отредактировал сам метод exist().

2023-03-13 07:05 UTC, db-exp approved these changes

2023-03-13 12:21 UTC, merged